#!/usr/bin/env python
"""Write docs/COVERAGE_WANTED.md: where a contributed system or cell would add the most.

Three lists, all derived from the data so the page cannot drift from it:

  1. the most-starred systems in the sampling frame (data/coding_frame.csv) that are not coded yet;
  2. the dimensions with the highest `not_reported` rate in the release (data/systems.json), with
     the field-weighted rate beside it when data/analysis/under_reporting_by_dimension.csv exists;
  3. the released systems that were coded outside the stratified draw and so carry weight 0.

Run:  python scripts/coverage_wanted.py [--top 30] [--out docs/COVERAGE_WANTED.md] [--check]
      --check exits 1 if the page on disk differs from what the data gives (for CI).
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRAME = ROOT / "data" / "coding_frame.csv"
SYSTEMS = ROOT / "data" / "systems.json"
DIMENSIONS = ROOT / "schema" / "dimensions.json"
UNDER_REPORTING = ROOT / "data" / "analysis" / "under_reporting_by_dimension.csv"
PASS2 = ROOT / "data" / "coded" / "json_pass2"
OUT = ROOT / "docs" / "COVERAGE_WANTED.md"


def _stars(row: dict) -> int:
    try:
        return int(float(row.get("stars") or 0))
    except ValueError:
        return 0


def uncoded_by_stars(frame: list[dict], released: set[str], top: int) -> list[dict]:
    """Frame systems neither flagged coded nor released, most-starred first (ties by id)."""
    rows = [r for r in frame if r.get("coded") != "1" and r["system_id"] not in released
            and _stars(r) > 0]
    rows.sort(key=lambda r: (-_stars(r), r["system_id"]))
    return rows[:top]


def not_reported_rates(systems: list[dict], dims: list[dict]) -> list[dict]:
    """Per dimension: cells, unresolved, not_reported, and the rate over settled cells."""
    out = []
    for d in dims:
        n = unresolved = nr = 0
        for s in systems:
            cell = (s.get("coding") or {}).get(d["key"])
            if not isinstance(cell, dict):
                continue
            n += 1
            if cell.get("unresolved"):
                unresolved += 1
            elif cell.get("not_reported"):
                nr += 1
        base = n - unresolved
        out.append({"id": d["id"], "key": d["key"], "layer": d["layer"], "cells": n,
                    "unresolved": unresolved, "not_reported": nr,
                    "rate": nr / base if base else 0.0})
    return out


def weighted_rates(path: Path) -> dict[str, tuple[float, float]]:
    """key -> (weighted rate, design SE), or {} when the analysis file is absent."""
    if not path.exists():
        return {}
    with path.open(newline="", encoding="utf-8") as f:
        return {r["key"]: (float(r["rate_weighted"]), float(r["se_weighted"]))
                for r in csv.DictReader(f) if r.get("rate_weighted")}


def outside_draw(systems: list[dict], frame: list[dict]) -> list[dict]:
    """Released systems whose frame row is not flagged coded (or that have no frame row)."""
    by_id = {r["system_id"]: r for r in frame}
    out = []
    for s in systems:
        row = by_id.get(s["id"])
        if row is None or row.get("coded") != "1":
            out.append({"id": s["id"], "name": s.get("name", ""),
                        "stratum": row.get("stratum", "") if row else "none",
                        "in_frame": row is not None})
    out.sort(key=lambda r: r["id"])
    return out


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(frame: list[dict], systems: list[dict], dims_doc: dict, weighted: dict,
           double_coded: set[str], top: int) -> str:
    layers = {x["id"]: x["name"] for x in dims_doc["layers"]}
    released = {s["id"] for s in systems}
    strata: dict[str, list[int]] = {}
    for r in frame:
        size_coded = strata.setdefault(r.get("stratum", "?"), [0, 0])
        size_coded[0] += 1
        size_coded[1] += r.get("coded") == "1"
    not_coded = sum(1 for r in frame if r.get("coded") != "1" and r["system_id"] not in released)
    wanted = uncoded_by_stars(frame, released, top)
    rates = sorted(not_reported_rates(systems, dims_doc["dimensions"]),
                   key=lambda r: (-weighted.get(r["key"], (r["rate"], 0))[0], -r["rate"], r["id"]))
    outside = outside_draw(systems, frame)
    cells = sum(len(s.get("coding") or {}) for s in systems)

    issues = "https://github.com/harness-db/harness-db/issues/new?template="
    lines: list[str] = ["# Coverage wanted", ""]
    lines.append("<!-- Generated by scripts/coverage_wanted.py from data/coding_frame.csv, "
                 "data/systems.json and schema/dimensions.json. Do not edit by hand; "
                 "rerun the script. -->")
    lines.append("")
    lines.append(f"HARNESS-DB codes {len(systems):,} of the {len(frame):,} systems in its sampling "
                 f"frame, on {len(dims_doc['dimensions'])} dimensions ({cells:,} cells). This page "
                 "lists where a contribution adds the most. To contribute, follow "
                 "[CONTRIBUTING.md](../CONTRIBUTING.md#add-or-update-a-system). To claim an item so "
                 f"two people do not code the same system, open an [add a system]({issues}"
                 "add_system.yml) issue first.")
    lines.append("")

    lines += ["## 1. Systems in the frame that are not coded yet", ""]
    lines.append("The frame was coded as a stratified sample. Stratum H (high visibility) is "
                 "coded completely; the other two were sampled:")
    lines += ["", "| stratum | systems in frame | flagged coded |", "|---|---:|---:|"]
    for k in sorted(strata):
        lines.append(f"| {k} | {strata[k][0]:,} | {strata[k][1]:,} |")
    lines.append("")
    lines.append(f"{not_coded:,} frame systems are neither coded nor released. The {len(wanted)} "
                 "most-starred of them (by the star count recorded in the frame) are below. A "
                 "contributed coding enters the next release as an unweighted addition: it was not "
                 "drawn by the sample, so like the systems in section 3 it carries weight 0 in "
                 "field-level estimates.")
    lines += ["", "| # | system id | name | stratum | stars | repository |",
              "|---:|---|---|---|---:|---|"]
    for i, r in enumerate(wanted, 1):
        lines.append(f"| {i} | `{r['system_id']}` | {_cell(r.get('name', ''))} | "
                     f"{r.get('stratum', '')} | {_stars(r):,} | {_cell(r.get('repo_url', ''))} |")
    lines.append("")

    wcol = bool(weighted)
    lines += ["## 2. Dimensions where the sources are most often silent", ""]
    intro = ("A `not_reported` cell means the coder read the sources and they do not say. Evidence "
             "that settles one of these cells, a verbatim quote with a locator at a pinned commit, "
             "is the most useful single contribution: it is where the dataset is thinnest. "
             "Rate = `not_reported` / (cells - `unresolved`).")
    if wcol:
        intro += (" The field-weighted rate (± design SE) uses the sampling weights and is the one "
                  "the paper reports; the table is sorted by it.")
    lines += [intro, ""]
    whead, wrule = ("not reported (field-weighted) | ", "---:|") if wcol else ("", "")
    lines.append(f"| dimension | layer | not reported (coded set) | {whead}cells not reported |")
    lines.append(f"|---|---|---:|{wrule}---:|")
    for r in rates:
        w = weighted.get(r["key"])
        wtxt = (f" {_pct(w[0])} ± {100 * w[1]:.1f} |" if w else " n/a |") if wcol else ""
        lines.append(f"| {r['id']} `{r['key']}` | {r['layer']} {layers[r['layer']]} | "
                     f"{_pct(r['rate'])} |{wtxt} {r['not_reported']:,} |")
    lines.append("")
    lines.append(f"To add evidence for one cell, open a [wrong cell]({issues}wrong_cell.yml) issue "
                 "with the quote and locator. Turning `not_reported` into a value is a correction "
                 "like any other.")
    lines.append("")

    lines += ["## 3. Coded systems outside the stratified draw", ""]
    lines.append(f"{len(outside)} released systems were coded for reasons other than the draw "
                 "(several are benchmark reference agents, coded because the reference-set recall "
                 "check needed them). They are in the release and count in every unweighted "
                 "statement, but their inclusion probability is not the design one, so every "
                 "field-level (weighted) estimate gives them weight 0. The stratum shown is the one "
                 "the frame assigns; the draw did not select them.")
    lines.append("")
    lines.append("What would help: an independent second reading of each, so that they can join "
                 "the reliability sample, and reports of any cell that looks wrong.")
    lines += ["", "| system id | name | stratum in frame | second reading on file |",
              "|---|---|---|---|"]
    for r in outside:
        stratum = r["stratum"] if r["in_frame"] else "not in frame"
        second = "yes" if r["id"] in double_coded else "no"
        lines.append(f"| `{r['id']}` | {_cell(r['name'])} | {stratum} | {second} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--top", type=int, default=30, help="how many uncoded systems to list")
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the page on disk is not what the data gives")
    args = ap.parse_args()

    with FRAME.open(newline="", encoding="utf-8") as f:
        frame = list(csv.DictReader(f))
    systems = json.loads(SYSTEMS.read_text(encoding="utf-8"))
    dims_doc = json.loads(DIMENSIONS.read_text(encoding="utf-8"))
    double_coded = {p.stem for p in PASS2.glob("*.json")} if PASS2.exists() else set()
    text = render(frame, systems, dims_doc, weighted_rates(UNDER_REPORTING), double_coded,
                  args.top)

    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != text:
            print(f"{args.out} is stale; run python scripts/coverage_wanted.py")
            return 1
        print(f"{args.out} is current")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
