#!/usr/bin/env python
"""Export the frozen candidate set for title/abstract screening (plan Phase 3, task A1).

Reads ``data/raw/candidates.csv`` (output of ``scripts/dedupe.py``) and writes

* ``data/screening/rayyan_import.ris`` - one RIS record per candidate (TY, TI, AB, AU, PY,
  DO, UR, and the candidate id in both ``ID`` and ``N1`` so votes can be joined back);
* ``data/screening/asreview_import.csv`` - columns ``record_id, title, abstract, doi, url,
  year, source, included`` with ``included = 1`` for the known-item ids
  (``data/raw/known_items.txt``, matched on arXiv id) and blank otherwise;
* ``data/screening/import_instructions.md`` - the exact Rayyan and ASReview steps.

Authors are not in ``candidates.csv``; they are looked up from the raw JSONL files in
``data/raw/`` by the canonical record id (all of them, so every merged cluster gets the
authors of its canonical record).

Usage:
    python scripts/export_screening.py [--candidates data/raw/candidates.csv]
        [--raw-dir data/raw] [--out-dir data/screening] [--known data/raw/known_items.txt]
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts" / "harvest"))
from common import normalize_arxiv_id, read_jsonl

PAPER_SOURCES = {"arxiv", "acl", "openreview", "s2", "openalex", "s2_snowball"}
_WS = re.compile(r"\s+")


def clean(s: str | None) -> str:
    return _WS.sub(" ", (s or "")).strip()


def load_authors(raw_dir: Path) -> dict[str, list[str]]:
    authors: dict[str, list[str]] = {}
    for path in sorted(raw_dir.glob("*.jsonl")):
        for r in read_jsonl(path):
            a = r.get("authors") or []
            if a and r.get("id") not in authors:
                authors[r["id"]] = [clean(x) for x in a if clean(x)]
    return authors


def load_known(path: Path) -> set[str]:
    ids: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            aid = normalize_arxiv_id(line.split("\t")[0])
            if aid:
                ids.add(aid)
    return ids


def ris_record(row: dict[str, str], authors: list[str]) -> str:
    ty = "JOUR" if row["source"] in PAPER_SOURCES else "GEN"
    lines = [f"TY  - {ty}", f"TI  - {clean(row['title']) or '(untitled)'}"]
    for a in authors:
        lines.append(f"AU  - {a}")
    if row.get("year") and re.fullmatch(r"\d{4}", row["year"]):
        lines.append(f"PY  - {row['year']}")
    if clean(row.get("abstract")):
        lines.append(f"AB  - {clean(row['abstract'])}")
    if clean(row.get("venue")):
        lines.append(f"JO  - {clean(row['venue'])}")
    if row.get("doi"):
        lines.append(f"DO  - {row['doi']}")
    if row.get("url"):
        lines.append(f"UR  - {row['url']}")
    lines.append(f"ID  - {row['id']}")
    lines.append(f"N1  - harness-db id: {row['id']}; source: {row['source']}; sources_all: {row.get('sources_all', '')}; arxiv: {row.get('arxiv_id', '')}")
    lines.append("ER  - ")
    return "\n".join(lines) + "\n\n"


INSTRUCTIONS = """# Screening imports — Rayyan (dual blinded) and ASReview (prioritisation for screener 1)

Generated by `scripts/export_screening.py` on {date} from `data/raw/candidates.csv`
({n} candidates; {n_known} of the 48 known items present and pre-labelled `included = 1`).

## Rayyan (the record of the two human votes and of Cohen's kappa)

1. Sign in at https://rayyan.ai (free tier). **New review** → name `HARNESS-Review title/abstract
   screening (search frozen 2026-09-16)`, type *Systematic review*.
2. **Upload** `data/screening/rayyan_import.ris` (RIS). {n} records. Rayyan reports duplicates it
   detects; do **not** merge them inside Rayyan — dedupe was done by `scripts/dedupe.py` and the
   PRISMA counts come from there. Ignore Rayyan's duplicate panel.
3. **Invite screener 2** (Review settings → Collaborators → *Invite*, role *Collaborator*). They
   need their own free account.
4. **Blind mode ON** (Review settings → *Blind mode*). Keep it on until both screeners have
   finished the whole set; only then turn it off to see conflicts. Do not discuss individual
   records while blind mode is on.
5. **Labels.** Rayyan's built-in decisions are *Include / Exclude / Maybe*; use *Maybe* for the
   protocol's `unsure`. Add the five exclusion reasons as Rayyan *Reasons* (Review settings →
   Reasons) with exactly these names, matching protocol §4.8 codes:
   `out_of_scope`, `no_harness_description`, `duplicate_system`, `not_retrievable`, `other`.
   At the title/abstract stage nearly every exclusion is `out_of_scope`; add the sub-reason as a
   Rayyan *Label* when it is obvious from the abstract (`no_loop`, `no_actions`,
   `component_only`, `framework_no_default`, `benchmark_only`, `training_only`, `embodied`,
   `date`), otherwise leave the sub-reason for full-text screening.
6. Screener 1 screens in the order ASReview proposes (below) and records the decision in Rayyan
   (ASReview is the prioritiser, Rayyan is the record). Screener 2 screens in Rayyan's default
   (random-shuffled) order — set *Sort → Random* once and keep it.
7. When both are done: blind mode OFF → *Conflicts* view. Export all decisions (Review →
   *Export* → CSV, include labels and reasons) to `data/screening/rayyan_export_<date>.csv`;
   `scripts/kappa.py votes` computes kappa from the two decision columns; the join key is the
   `ID`/`N1` field = harness-db candidate id. Adjudication decisions and reasons go in
   `data/screening/adjudication_log.md`.

## ASReview (active-learning prioritisation for screener 1 only)

1. `pip install asreview` (v1.x or v2.x) and start `asreview lab` (opens http://localhost:5000).
2. **New project** → *Screening* mode; name `HARNESS-Review TA screening`.
3. **Import** `data/screening/asreview_import.csv`. Columns are recognised automatically
   (`title`, `abstract`, `doi`, `url`, `included`). {n} records.
4. **Prior knowledge.** ASReview picks up the `included` column: the {n_known} known items are
   the relevant priors. Add the 20 irrelevant priors listed in
   `data/screening/prior_knowledge.csv` (label 0) by searching each `record_id` / title in the
   prior-knowledge step and marking it *irrelevant* (`scripts/prioritise.py` produces that file
   and the reasons).
5. **Model:** keep the defaults (TF-IDF features, Naive Bayes classifier, max query strategy,
   dynamic resampling). Record the ASReview version and model settings in
   `data/screening/stopping_rule_log.md`.
6. **Stopping rule (registered):** stop when **100 consecutive records have been marked
   irrelevant after every known item (the {n_known} pre-labelled priors) has been found**. Log
   each session in `data/screening/stopping_rule_log.md` (date, records screened, longest run
   of consecutive irrelevant, known items found so far). Do not stop earlier, and do not change
   the rule without a protocol amendment.
7. Export the ASReview project (*Export → Dataset with labels*) to
   `data/screening/asreview_export_<date>.csv` at the end; the `record_id` column joins back to
   `candidates.csv`.

## Files

| file | records | purpose |
|---|---:|---|
| `data/screening/rayyan_import.ris` | {n} | Rayyan upload (both screeners) |
| `data/screening/asreview_import.csv` | {n} | ASReview upload (screener 1); `included` = 1 for {n_known} known items |
| `data/screening/prior_knowledge.csv` | 48 + 20 | positive and negative priors with reasons (`scripts/prioritise.py`) |
| `data/screening/stopping_rule_log.md` | — | registered stopping rule and per-session log |
| `data/screening/llm_votes.csv` | — | LLM third vote (`scripts/screen_llm.py`); never merged into the human columns |
"""


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--candidates", default=str(REPO / "data/raw/candidates.csv"))
    p.add_argument("--raw-dir", default=str(REPO / "data/raw"))
    p.add_argument("--out-dir", default=str(REPO / "data/screening"))
    p.add_argument("--known", default=str(REPO / "data/raw/known_items.txt"))
    args = p.parse_args(argv)

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    with open(args.candidates, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    authors = load_authors(Path(args.raw_dir))
    known = load_known(Path(args.known))

    n_known = 0
    stats = Counter()
    with (out / "rayyan_import.ris").open("w", encoding="utf-8", newline="\n") as ris, (out / "asreview_import.csv").open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["record_id", "title", "abstract", "doi", "url", "year", "source", "included"])
        for r in rows:
            au = authors.get(r["id"], [])
            stats["with_authors"] += bool(au)
            ris.write(ris_record(r, au))
            inc = ""
            if r.get("arxiv_id") and normalize_arxiv_id(r["arxiv_id"]) in known:
                inc = "1"
                n_known += 1
            w.writerow([r["id"], clean(r["title"]), clean(r["abstract"]), r.get("doi", ""), r.get("url", ""), r.get("year", ""), r["source"], inc])
    from datetime import UTC, datetime

    (out / "import_instructions.md").write_text(
        INSTRUCTIONS.format(date=datetime.now(UTC).strftime("%Y-%m-%d"), n=f"{len(rows):,}", n_known=n_known), encoding="utf-8"
    )
    summary = {"candidates": len(rows), "ris_records": len(rows), "asreview_rows": len(rows), "known_items_prelabelled": n_known, "with_authors": stats["with_authors"], "out_dir": str(out)}
    print("SUMMARY " + json.dumps(summary))
    return 0


if __name__ == "__main__":
    sys.exit(main())
